print("Do you want to take this quiz?\nAnswer Yes (y) or No (n)")
answer = input()
print("How old are you?", end = ' ')
age = input()
print("How tall are you?", end = ' ')
height = input()
print("How much do you weigh?", end = ' ')
weight = input()
print(f"""You responded {answer} to the quiz.
So you are {age} years old, {height} tall and {weight} heavy.""")
